# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- dev

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'sc-arm-u7'
    KeyVaultName: 'kvteam2'
    SecretsFilter: 'vmpasswordu7'
    RunAsPreJob: true

- task: AzureCLI@2
  inputs:
    azureSubscription: 'sc-arm-u7'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az vm create --resource-group rgteam2 --name demovmu7 --image win2016datacenter --admin-username u07 --admin-password $(vmpasswordu7)'

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
